language: python

matrix:
    include:
        - python: 3.5
        - python: 3.6

before_install:
    - pip install pip --upgrade
    - pip install pytest pytest-cov pytest-pep8 --upgrade

install:
    - pip install .

script:
    - pytest
